"""The two release scripts, run against throwaway repositories.

`scripts/bump-version.sh` and `scripts/tag-release.sh` cut a release with no
one reading the diff closely, so what they refuse matters as much as what they
do. Each test builds a repository shaped like this one where it matters -- the
four files that carry the version, a commit on main, and an `origin` -- with a
local bare repository standing in for GitHub, so nothing reaches the network and
the push can be inspected afterwards.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = ("bump-version.sh", "tag-release.sh")

CARGO_TOML = """\
[package]
name = "uphold"
version = "1.2.3"
edition = "2021"

[dependencies]
"""

CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "uphold"
version = "1.2.3"
"""

README = """\
# uphold

Released as 1.2.3 is prose, not a pin, and is left alone.

```sh
cargo install --git https://github.com/HackingGate/uphold --tag v1.2.3
```

```yaml
repos:
  - repo: https://github.com/HackingGate/uphold
    rev: v1.2.3
```

```yaml
remotes:
  - git_url: https://github.com/HackingGate/uphold
    ref: v1.2.3
```
"""

LEFTHOOK = """\
# uphold's lefthook manifest.
#
#   remotes:
#     - git_url: https://github.com/HackingGate/uphold
#       ref: v1.2.3
#       configs:
#         - hooks/lefthook.yml
pre-commit:
  commands: {}
"""

VERSION_FILES = ("Cargo.toml", "Cargo.lock", "README.md", "hooks/lefthook.yml")


class Sandbox:
    """A working repository with a bare `origin`, and a git that sees neither
    the developer's global configuration nor the hook that is running us."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.origin = root / "origin.git"
        self.work = root / "work"
        home = root / "home"
        home.mkdir()
        config = home / "gitconfig"
        config.write_text(
            textwrap.dedent(
                """\
                [user]
                    name = Release Test
                    email = release@example.invalid
                [init]
                    defaultBranch = main
                [commit]
                    gpgSign = false
                [tag]
                    gpgSign = false
                """
            ),
            encoding="utf-8",
        )
        # A hook runner exports GIT_DIR and friends; inherited, they would point
        # every git call below at the repository under test.
        self.env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
        self.env.update(GIT_CONFIG_GLOBAL=str(config), GIT_CONFIG_NOSYSTEM="1")

    def git(self, *args: str, cwd: Path | None = None) -> str:
        return subprocess.run(
            ["git", *args],
            cwd=cwd or self.work,
            env=self.env,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()

    def build(self, subject: str = "Prepare uphold 1.2.3 (#7)") -> None:
        self.git("init", "-q", "--bare", str(self.origin), cwd=self.root)
        self.git("init", "-q", str(self.work), cwd=self.root)
        for name, body in {
            "Cargo.toml": CARGO_TOML,
            "Cargo.lock": CARGO_LOCK,
            "README.md": README,
            "hooks/lefthook.yml": LEFTHOOK,
            "src/main.rs": "fn main() {}\n",
        }.items():
            path = self.work / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")
        (self.work / "scripts").mkdir()
        for script in SCRIPTS:
            shutil.copy2(REPO / "scripts" / script, self.work / "scripts" / script)
        self.git("add", "-A")
        self.git("commit", "-q", "-m", subject)
        self.git("remote", "add", "origin", str(self.origin))
        self.git("push", "-q", "origin", "main")
        # The fetch the scripts make; done here first so the remote-tracking
        # refs it creates are part of the state a refused run must preserve.
        self.git("fetch", "-q", "origin", "--tags")

    def run(self, script: str, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["bash", str(self.work / "scripts" / script), *args],
            cwd=self.work,
            env=self.env,
            capture_output=True,
            text=True,
            check=False,
        )

    def state(self) -> tuple[str, str, str, str]:
        """Everything a refused run must leave as it found: the branch, its
        commit, the working tree, and the refs on both sides."""
        return (
            self.git("rev-parse", "--abbrev-ref", "HEAD"),
            self.git("status", "--porcelain"),
            self.git("for-each-ref"),
            self.git("for-each-ref", cwd=self.origin),
        )


def _sandbox(case: unittest.TestCase, **build) -> Sandbox:
    tmp = tempfile.TemporaryDirectory()
    case.addCleanup(tmp.cleanup)
    box = Sandbox(Path(tmp.name))
    box.build(**build)
    return box


@unittest.skipUnless(shutil.which("git") and shutil.which("bash"), "needs git and bash")
class BumpVersion(unittest.TestCase):
    @unittest.skipUnless(shutil.which("cargo"), "the lock is checked by cargo")
    def test_changes_exactly_the_version_lines_and_commits_them(self) -> None:
        box = _sandbox(self)
        base = box.git("rev-parse", "HEAD")

        result = box.run("bump-version.sh", "1.3.0")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(box.git("rev-parse", "--abbrev-ref", "HEAD"), "prepare-1.3.0")
        self.assertEqual(box.git("rev-parse", "HEAD~1"), base)
        self.assertEqual(box.git("log", "-1", "--format=%s"), "Prepare uphold 1.3.0")
        self.assertEqual(box.git("log", "-1", "--format=%b"), "")
        self.assertEqual(box.git("status", "--porcelain"), "")

        numstat = {
            line.split("\t")[2]: tuple(line.split("\t")[:2])
            for line in box.git("diff", "--numstat", "HEAD~1", "HEAD").splitlines()
        }
        self.assertEqual(
            numstat,
            {
                "Cargo.toml": ("1", "1"),
                "Cargo.lock": ("1", "1"),
                "README.md": ("3", "3"),
                "hooks/lefthook.yml": ("1", "1"),
            },
        )
        for name in VERSION_FILES:
            text = (box.work / name).read_text(encoding="utf-8")
            self.assertNotIn('"1.2.3"', text, name)
            self.assertNotIn("v1.2.3", text, name)
        readme = (box.work / "README.md").read_text(encoding="utf-8")
        self.assertIn("Released as 1.2.3 is prose", readme)
        self.assertEqual(readme.count("v1.3.0"), 3)

        # Nothing left the machine; the next steps are printed instead.
        self.assertNotIn("prepare-1.3.0", box.git("for-each-ref", cwd=box.origin))
        self.assertIn("git push -u origin prepare-1.3.0", result.stdout)
        self.assertIn(
            'gh pr create --title "Prepare uphold 1.3.0" --body "Version bump."',
            result.stdout,
        )

    def test_refuses_a_version_that_is_not_plain(self) -> None:
        box = _sandbox(self)
        before = box.state()
        for bad in ("1.3", "v1.3.0", "1.3.0-rc.1", "01.3.0", "1.3.0.0", "", "x.y.z"):
            with self.subTest(version=bad):
                result = box.run("bump-version.sh", bad)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn("not a plain version", result.stderr)
                self.assertEqual(box.state(), before)

    def test_refuses_a_version_that_is_not_greater(self) -> None:
        box = _sandbox(self)
        before = box.state()
        for stale in ("1.2.3", "1.2.2", "1.1.9", "0.9.9"):
            with self.subTest(version=stale):
                result = box.run("bump-version.sh", stale)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(
                    "is not greater than the current version 1.2.3", result.stderr
                )
                self.assertEqual(box.state(), before)

    def test_an_unexpected_line_count_restores_the_files_and_fails(self) -> None:
        box = _sandbox(self)
        readme = box.work / "README.md"
        readme.write_text(
            readme.read_text(encoding="utf-8") + "\n    rev: v1.2.3\n", encoding="utf-8"
        )
        box.git("commit", "-q", "-am", "A fourth pin")
        before = box.state()

        result = box.run("bump-version.sh", "1.3.0")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("README.md: expected 3 line(s) changed, got '4 4'", result.stderr)
        self.assertEqual(box.state(), before)

    def test_refuses_a_dirty_tree(self) -> None:
        box = _sandbox(self)
        readme = box.work / "README.md"
        edited = readme.read_text(encoding="utf-8") + "\nAn edit in progress.\n"
        readme.write_text(edited, encoding="utf-8")
        before = box.state()

        result = box.run("bump-version.sh", "1.3.0")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("uncommitted changes", result.stderr)
        self.assertEqual(box.state(), before)
        self.assertEqual(readme.read_text(encoding="utf-8"), edited)


@unittest.skipUnless(shutil.which("git") and shutil.which("bash"), "needs git and bash")
class TagRelease(unittest.TestCase):
    def test_refuses_when_main_is_not_the_prep_commit(self) -> None:
        for subject in (
            "Something merged after the prep (#8)",
            "Prepare uphold 1.2.4 (#7)",
            "Prepare uphold 1.2.3",
            "Prepare uphold 1.2.3 (#7) and more",
        ):
            with self.subTest(subject=subject):
                box = _sandbox(self, subject=subject)
                before = box.state()
                result = box.run("tag-release.sh")
                self.assertNotEqual(result.returncode, 0)
                self.assertIn("not 'Prepare uphold 1.2.3 (#N)'", result.stderr)
                self.assertEqual(box.state(), before)

    def test_refuses_a_tag_that_exists_locally(self) -> None:
        box = _sandbox(self)
        box.git("tag", "v1.2.3")
        before = box.state()

        result = box.run("tag-release.sh")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("v1.2.3 already exists locally", result.stderr)
        self.assertEqual(box.state(), before)

    def test_refuses_a_tag_that_exists_on_origin(self) -> None:
        box = _sandbox(self)
        # Pushed from another clone, so this one has never seen it.
        box.git("tag", "-a", "v1.2.3", "-m", "uphold 1.2.3", "HEAD")
        box.git("push", "-q", "origin", "refs/tags/v1.2.3")
        box.git("tag", "-d", "v1.2.3")
        remote_before = box.git("for-each-ref", cwd=box.origin)

        result = box.run("tag-release.sh")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("v1.2.3 already exists", result.stderr)
        self.assertEqual(box.git("for-each-ref", cwd=box.origin), remote_before)

    def test_dry_run_changes_nothing(self) -> None:
        box = _sandbox(self)
        sha = box.git("rev-parse", "HEAD")
        before = box.state()

        result = box.run("tag-release.sh", "--dry-run")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(f'git tag -a v1.2.3 -m "uphold 1.2.3" {sha}', result.stdout)
        self.assertIn("git push origin refs/tags/v1.2.3", result.stdout)
        self.assertEqual(box.state(), before)

    def test_tags_the_prep_commit_and_pushes_only_that_tag(self) -> None:
        box = _sandbox(self)
        sha = box.git("rev-parse", "HEAD")
        # Local refs a careless push would publish along with the release.
        box.git("tag", "v0.0.1-scratch")
        box.git("branch", "unpushed")

        result = box.run("tag-release.sh")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(box.git("cat-file", "-t", "v1.2.3"), "tag")
        self.assertEqual(box.git("rev-parse", "v1.2.3^{commit}"), sha)
        self.assertEqual(
            box.git("for-each-ref", "--format=%(contents)", "refs/tags/v1.2.3"),
            "uphold 1.2.3",
        )
        self.assertIn("tag v1.2.3", result.stdout)

        remote = box.git("for-each-ref", "--format=%(refname)", cwd=box.origin)
        self.assertEqual(remote.splitlines(), ["refs/heads/main", "refs/tags/v1.2.3"])
        self.assertEqual(
            box.git("rev-parse", "refs/tags/v1.2.3", cwd=box.origin),
            box.git("rev-parse", "refs/tags/v1.2.3"),
        )


if __name__ == "__main__":
    unittest.main()
