#!/usr/bin/env python3
"""Generate the quick-reference document and the name index from TOML records."""

from __future__ import annotations

import argparse
import json
import sys

from analysis import ANALYZER
from catalog import ROOT, alias_index, load_catalog, name_entries
from validate import RUNGS

OUTPUT = ROOT / "QUICK_REFERENCE.md"
INDEX_OUTPUT = ROOT / "name-index.json"


def cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def link(record: dict) -> str:
    return f"[{cell(record['title'])}](principles/{record['id']}.toml)"


def grouped(records: list[dict], values, order=None) -> list[str]:
    """One line per value, listing every record that carries it.

    Values sort by their folded spelling, with the raw spelling as the tie-break,
    unless `order` gives them a position of their own; records keep the order
    they arrive in, so a regenerated file is a diff only when the catalog
    changed.
    """
    groups: dict[str, list[dict]] = {}
    for record in records:
        for value in values(record):
            groups.setdefault(value, []).append(record)
    if order is None:

        def key(value):
            return (value.casefold(), value)

    else:

        def key(value):
            return order.index(value)

    return [
        f"- **{cell(value)}**: " + ", ".join(link(record) for record in groups[value])
        for value in sorted(groups, key=key)
    ]


NO_RUNG = "none stated"


def rungs_of(record: dict) -> list[str]:
    """The rungs a record says a check can see it at, or the one word for none."""
    return record["enforcement"].get("rung") or [NO_RUNG]


def render() -> str:
    records = sorted(load_catalog(), key=lambda item: item["title"].casefold())
    lines = [
        "# Engineering principles — quick reference",
        "",
        "Generated from `principles/*.toml`. Do not edit this file directly.",
        "",
        "| principle | also known as | kind | domains | concise claim | enforcement |",
        "|---|---|---|---|---|---|",
    ]
    for record in records:
        enforcement = record["enforcement"]
        aliases = "; ".join(cell(alias) for alias in record["aliases"]) or "—"
        summary = cell(record["summary"])
        domains = ", ".join(cell(domain) for domain in record["domains"])
        level = enforcement["level"]
        automation = enforcement["automatable"]
        rung = enforcement.get("rung")
        observed = f"; rung: {', '.join(rung)}" if rung else ""
        lines.append(
            f"| {link(record)} | {aliases} | {record['kind']} | {domains} | {summary} | {level}; {automation}{observed} |"
        )

    # Two groupings of the same records, for a reader who arrives with "which
    # records are heuristics" or "what applies to data" rather than a name.
    # `kind` and `domains` answer different questions (ADR 0011), so each gets
    # its own list rather than one being folded into the other.
    lines.extend(["", "## By kind", ""])
    lines.extend(grouped(records, lambda record: [record["kind"]]))
    lines.extend(["", "## By domain", ""])
    lines.extend(grouped(records, lambda record: record["domains"]))

    # The third question a record answers (ADR 0011): at which rung a gate can
    # see it. In ladder order, and with the records that state no rung listed
    # last under one word, so the line a reader wants -- what a reviewer alone
    # can hold -- is a line and not a subtraction.
    lines.extend(["", "## By rung", ""])
    lines.extend(grouped(records, rungs_of, order=(*RUNGS, NO_RUNG)))

    # This is a rendering of `catalog.alias_index()`, not a second construction
    # of it: the mapping is a value the catalog holds, and this loop spends it on
    # strings at the last possible moment. Anything that wants the mapping reads
    # name-index.json or imports the function; nothing should read these rows
    # back, which is why the escaping below is allowed to be lossy.
    lines.extend(
        [
            "",
            "## Alias index",
            "",
            "The names people actually use, against the record that answers them.",
            "Machine-readable, and without this table's escaping, in"
            " [`name-index.json`](name-index.json).",
            "",
            "| also known as | record |",
            "|---|---|",
        ]
    )
    for entry in alias_index(records):
        lines.append(f"| {cell(entry.name)} | [{cell(entry.title)}]({entry.path}) |")

    lines.extend(
        [
            "",
            "## Review rule",
            "",
            "Before applying a principle, read its scope, costs, conflicts, and",
            "`failure_when_overapplied` fields. The table above is an index, not policy.",
            "",
        ]
    )
    return "\n".join(lines)


# The index a consumer reads. QUICK_REFERENCE.md is for a human and pays for it
# in escaping and layout; this file carries the same mapping in the form the
# catalog holds it, so answering "which record owns this name" costs a `json.load`
# rather than a Markdown parse plus an un-escaping of `cell()`.
#
# It stays narrow on purpose. Names, keys, and the id they resolve to -- not the
# records. A second file carrying prose would be the catalog in a second format,
# and `single-authoritative-source` is a record in it. `--check` keeps this file
# in the same staleness gate as the Markdown, so a stale index cannot be
# committed and no reader has to wonder which of the two is current.
def render_index() -> str:
    entries = name_entries()
    payload = {
        "version": 1,
        "generated_from": "principles/*.toml",
        "generator": "scripts/build_reference.py",
        "canonical": "principles/<id>.toml -- this file is generated; do not edit",
        "analyzer": ANALYZER,
        "names": [
            {
                "name": entry.name,
                "key": entry.key,
                "tokens": list(entry.tokens),
                "field": entry.field,
                "id": entry.record_id,
                "title": entry.title,
                "path": entry.path,
            }
            for entry in entries
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


ARTIFACTS = ((OUTPUT, render), (INDEX_OUTPUT, render_index))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if args.check:
        stale = []
        for path, renderer in ARTIFACTS:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != renderer():
                stale.append(path.relative_to(ROOT))
        if stale:
            names = ", ".join(str(path) for path in stale)
            print(
                f"{names} is stale; run scripts/build_reference.py",
                file=sys.stderr,
            )
            return 1
        print("generated files are current")
        return 0

    for path, renderer in ARTIFACTS:
        path.write_text(renderer(), encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
