//! The principle catalog, as the reconcile needs it.
//!
//! Compiled in rather than read off disk, for the reason the bundled rule sets
//! are: this binary runs in a CONSUMER's repository, which has a policy file
//! and a declaration and no copy of this catalog. A reader that went looking
//! for `principles/` beside the executable would find it only in the one
//! repository that does not need it.
//!
//! Four fields, and deliberately not the record. A reconcile asks whether a
//! claimed principle exists, whether it is deprecated, and whether its own
//! record says a machine can enforce it -- three questions with a yes or no
//! each. Everything else in a record is prose for a person building a rule, and
//! prose a tool holds is prose it has no condition on which to emit; see the
//! `enforcement-needs-a-trigger` record, which is in this catalog. `--explain`
//! reads the files themselves and stays where the prose is.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::Deserialize;

use crate::error::{Fatal, Result};

/// Every record, as `include_str!` pairs of id and TOML source.
///
/// Generated by no build script on purpose: a list a reader can see is a list a
/// reader can check against `ls principles/`, and
/// `tests::records_list_every_principle_file` below asserts the two agree, so
/// a record added to the directory and not to this list fails `cargo test`
/// rather than going quietly missing from every reconcile.
const RECORDS: &[(&str, &str)] = &[
    (
        "backpressure",
        include_str!("../principles/backpressure.toml"),
    ),
    (
        "complete-mediation",
        include_str!("../principles/complete-mediation.toml"),
    ),
    (
        "compromise-recording",
        include_str!("../principles/compromise-recording.toml"),
    ),
    (
        "confused-deputy",
        include_str!("../principles/confused-deputy.toml"),
    ),
    (
        "data-minimization",
        include_str!("../principles/data-minimization.toml"),
    ),
    (
        "defense-in-depth",
        include_str!("../principles/defense-in-depth.toml"),
    ),
    (
        "economy-of-mechanism",
        include_str!("../principles/economy-of-mechanism.toml"),
    ),
    (
        "end-to-end-principle",
        include_str!("../principles/end-to-end-principle.toml"),
    ),
    (
        "enforcement-needs-a-trigger",
        include_str!("../principles/enforcement-needs-a-trigger.toml"),
    ),
    (
        "explicit-unknown",
        include_str!("../principles/explicit-unknown.toml"),
    ),
    ("fail-fast", include_str!("../principles/fail-fast.toml")),
    (
        "fail-safe-defaults",
        include_str!("../principles/fail-safe-defaults.toml"),
    ),
    (
        "graceful-degradation",
        include_str!("../principles/graceful-degradation.toml"),
    ),
    (
        "high-cohesion-low-coupling",
        include_str!("../principles/high-cohesion-low-coupling.toml"),
    ),
    (
        "idempotency",
        include_str!("../principles/idempotency.toml"),
    ),
    (
        "information-hiding",
        include_str!("../principles/information-hiding.toml"),
    ),
    (
        "informed-consent",
        include_str!("../principles/informed-consent.toml"),
    ),
    (
        "least-astonishment",
        include_str!("../principles/least-astonishment.toml"),
    ),
    (
        "least-common-mechanism",
        include_str!("../principles/least-common-mechanism.toml"),
    ),
    (
        "least-privilege",
        include_str!("../principles/least-privilege.toml"),
    ),
    (
        "make-illegal-states-unrepresentable",
        include_str!("../principles/make-illegal-states-unrepresentable.toml"),
    ),
    (
        "mechanism-policy-separation",
        include_str!("../principles/mechanism-policy-separation.toml"),
    ),
    (
        "minimize-attack-surface",
        include_str!("../principles/minimize-attack-surface.toml"),
    ),
    (
        "observability",
        include_str!("../principles/observability.toml"),
    ),
    (
        "parameterize-do-not-enumerate",
        include_str!("../principles/parameterize-do-not-enumerate.toml"),
    ),
    (
        "psychological-acceptability",
        include_str!("../principles/psychological-acceptability.toml"),
    ),
    (
        "reversible-decisions",
        include_str!("../principles/reversible-decisions.toml"),
    ),
    (
        "separation-of-concerns",
        include_str!("../principles/separation-of-concerns.toml"),
    ),
    (
        "separation-of-privilege",
        include_str!("../principles/separation-of-privilege.toml"),
    ),
    (
        "single-authoritative-source",
        include_str!("../principles/single-authoritative-source.toml"),
    ),
    (
        "unix-composability",
        include_str!("../principles/unix-composability.toml"),
    ),
];

/// What a reconcile asks of one record.
#[derive(Debug, Clone, Deserialize)]
pub(crate) struct Record {
    pub id: String,
    #[serde(default)]
    pub status: String,
    #[serde(default)]
    pub enforcement: Enforcement,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct Enforcement {
    /// `"yes"`, `"partially"`, or `"no"`. Absent is not `"no"`: a record that says
    /// nothing has not refused, and treating silence as a refusal would fail a
    /// claim on grounds nobody wrote.
    #[serde(default)]
    pub automatable: Option<String>,
}

impl Record {
    pub(crate) fn deprecated(&self) -> bool {
        self.status == "deprecated"
    }

    /// Whether the record itself says no rule can enforce it.
    pub(crate) fn refuses_automation(&self) -> bool {
        self.automatable() == Some("no")
    }

    pub(crate) fn automatable(&self) -> Option<&str> {
        self.enforcement.automatable.as_deref()
    }
}

/// The catalog, parsed once.
///
/// A record that does not parse is a defect in this binary and not in the tree
/// being checked -- the file is compiled in, and `validate` refuses a malformed
/// one at commit time. It is still exit 2 rather than a crash, because the
/// contract a caller reads is the exit code: a checker that dies is a checker
/// whose answer nobody has, and the state for that is could-not-look. See the
/// `explicit-unknown` record.
fn catalog() -> Result<&'static BTreeMap<String, Record>> {
    static CATALOG: OnceLock<std::result::Result<BTreeMap<String, Record>, String>> =
        OnceLock::new();
    CATALOG
        .get_or_init(|| {
            let mut catalog = BTreeMap::new();
            for (id, source) in RECORDS {
                let record: Record = toml::from_str(source)
                    .map_err(|error| format!("bundled principle {id}: {error}"))?;
                if &record.id != id {
                    return Err(format!(
                        "bundled principle {id} carries the id {:?}",
                        record.id
                    ));
                }
                catalog.insert(record.id.clone(), record);
            }
            Ok(catalog)
        })
        .as_ref()
        .map_err(|error| Fatal::new(error.clone()))
}

pub(crate) fn get(id: &str) -> Result<Option<&'static Record>> {
    Ok(catalog()?.get(id))
}

/// Every id, for a caller reporting one that is not there.
pub(crate) fn ids() -> Result<Vec<&'static str>> {
    Ok(catalog()?.keys().map(String::as_str).collect())
}

/// The records a claim is ALLOWED to name -- the coverage denominator.
///
/// Not the `automatable = "yes"` ones. Those are the records a reviewer is
/// chased about in `--review`; this is the wider set a declaration may draw
/// from, which is everything the reconcile would not refuse: not deprecated,
/// and not `automatable = "no"`. Measuring against the narrower set understated
/// the denominator and, worse, dropped from the numerator every principle a
/// rule really does enforce whose record is `partial`.
pub(crate) fn claimable_ids() -> Result<Vec<&'static str>> {
    Ok(catalog()?
        .values()
        .filter(|record| !record.deprecated() && !record.refuses_automation())
        .map(|record| record.id.as_str())
        .collect())
}

/// Refuse a claim on an id the catalog does not define, in the words a person
/// can act on.
pub(crate) fn unknown(id: &str, known: usize) -> String {
    format!(
        "unknown principle id {id:?}; the catalog defines {known} of them, and \
         `uphold_check.py --list` prints every one"
    )
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    /// The record files as `scripts/catalog.py::principle_paths` sees them:
    /// every `*.toml` under `principles/` whose name does not start with `_`,
    /// by stem, sorted.
    fn files_on_disk() -> Vec<String> {
        let dir = PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/principles"));
        let mut stems: Vec<String> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .filter(|path| path.extension().is_some_and(|ext| ext == "toml"))
            .filter_map(|path| path.file_stem()?.to_str().map(str::to_owned))
            .filter(|stem| !stem.starts_with('_'))
            .collect();
        stems.sort();
        stems
    }

    /// The promise the doc comment on `RECORDS` makes. A record added to the
    /// directory and not to the list would otherwise be a file `validate.py`
    /// accepts and `uphold check` has never heard of, and the first anyone
    /// would learn of it is a consumer's claim refused as an unknown id. The
    /// comparison is over the whole list, in order, so a duplicated pair --
    /// which `BTreeMap::insert` would silently collapse -- fails here too.
    #[test]
    fn records_list_every_principle_file() {
        let listed: Vec<String> = RECORDS.iter().map(|(id, _)| (*id).to_owned()).collect();
        assert_eq!(
            listed,
            files_on_disk(),
            "RECORDS in src/catalog.rs and ls principles/*.toml disagree"
        );
    }

    /// Every bundled record parses and carries the id it is listed under.
    /// `validate.py` refuses a malformed file at commit; this is the same
    /// refusal at the point the binary would otherwise exit 2 on every run.
    #[test]
    fn every_bundled_record_parses() {
        let catalog = catalog().unwrap();
        assert_eq!(catalog.len(), RECORDS.len());
    }
}
